# This file contains templated variables to avoid repeating the same hard-coded values.
# Templated variables are denoted by the dollar curly braces token. The following details each templated variable that you can use:
# `starter_location`: This is an Azure location sourced from the `starter_location` variable. This can be used to set the location of resources.
# `default_postfix`: This is a string sourced from the variable `default_postfix`. This can be used to append to resource names for consistency.
# `root_parent_management_group_id`: This is the id of the management group that the ALZ hierarchy will be nested under.
# `subscription_id_identity`: The subscription ID of the subscription to deploy the identity resources to, sourced from the variable `subscription_id_identity`.
# `subscription_id_connectivity`: The subscription ID of the subscription to deploy the connectivity resources to, sourced from the variable `subscription_id_connectivity`.
# `subscription_id_management`: The subscription ID of the subscription to deploy the management resources to, sourced from the variable `subscription_id_management`.
archetypes: # `caf-enterprise-scale` module, add inputs as listed on the module registry where necessary.
  root_name: es1
  root_id: Enterprise-Scale1
  deploy_corp_landing_zones: true
  deploy_online_landing_zones: true
  default_location: eastus
  disable_telemetry: true
  deploy_management_resources: true
  default_tags:
    environment: dev
    costcenter: 12345
  configure_management_resources:
    location: eastus
    settings:
      security_center:
        config:
          email_security_contact: "security_contact@replace_me"
  custom_landing_zones:
    eucustomers:
      display_name: EU Customerssemi
      parent_management_group_id: es-landing-zones